### ISSUE TITLE
Could you please update API_URL to http://localhost:3000/api/v1 for localhost

### ISSUE THREAD

**Issue by Kashoid23** [VitaliyRdk/blog-app#2]
`export const API_URL = window.location.hostname === 'localhost' ? 'http://localhost:3000/api/v1' : '';`

**Comment by VitaliyRdk** [comment]
[Done](https://github.com/VitaliyRdk/blog-app/commit/bb169160362167d17326a798f11b42f583b02e42)

**Comment by Kashoid23** [comment]
Thanks! 🙏
